In [121]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.svm import SVR

from sklearn.metrics import *

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [122]:
path = "/content/drive/MyDrive/ev_battery_final_dataset.csv"
df = pd.read_csv(path)

df.head()

,cycle_count,avg_speed,avg_voltage,avg_temp,voltage_drop_rate,battery_state,battery_health,rul_cycles
0,960,71.307143,238.702885,28.121886,0.095285,Degrading,44.278099,1037.401971
1,1195,42.195261,243.183502,30.178000,0.093286,Warning,32.590667,211.034074
2,1144,63.967113,211.622350,30.901822,0.107619,Warning,32.472082,306.271450
3,221,83.295489,244.863909,36.828133,0.092278,Degrading,63.661179,2735.033549
4,566,44.926099,220.267769,31.075895,0.043184,Degrading,61.182354,2094.262167

In [123]:
print(df.shape)
df.info()
df.describe()

(1200, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cycle_count        1200 non-null   int64
 1   avg_speed          1200 non-null   float64
 2   avg_voltage        1200 non-null   float64
 3   avg_temp           1200 non-null   float64
 4   voltage_drop_rate  1200 non-null   float64
 5   battery_state      1200 non-null   object
 6   battery_health     1200 non-null   float64
 7   rul_cycles         1200 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 75.1+ KB

,cycle_count,avg_speed,avg_voltage,avg_temp,voltage_drop_rate,battery_health,rul_cycles
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,663.483333,62.284000,230.645181,34.797906,0.069272,50.468664,1560.461711
std,326.759335,12.962189,11.401037,4.071805,0.028845,14.397511,1004.353786
min,100.000000,40.008478,210.017711,28.002611,0.020075,18.546756,50.000000
25%,366.500000,50.644868,221.115555,31.271673,0.044224,38.312784,679.633546
50%,693.500000,62.423270,231.236454,34.650859,0.068888,49.792854,1503.894925
75%,937.750000,73.569807,240.436513,38.384855,0.094123,62.033017,2431.435490
max,1199.000000,84.868517,249.988552,41.966720,0.119905,84.489652,3655.099415

In [124]:
le = LabelEncoder()
df["battery_state_enc"] = le.fit_transform(df["battery_state"])

In [125]:
X = df[[
    "cycle_count",
    "avg_speed",
    "avg_voltage",
    "avg_temp",
    "voltage_drop_rate"
]]

y = df["battery_health"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [126]:
model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Linear Regression R2:", r2_score(y_test, pred))

Linear Regression R2: 1.0

In [127]:
rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

pred = rf.predict(X_test)

print("Random Forest R2:", r2_score(y_test, pred))

Random Forest R2: 0.9945805638826013

In [128]:
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

svr = SVR(C=100)
svr.fit(X_train_s, y_train)

pred = svr.predict(X_test_s)

print("SVR R2:", r2_score(y_test, pred))

SVR R2: 0.9996894911868991

In [129]:
y = df["rul_cycles"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [130]:
lr = LinearRegression()
lr.fit(X_train, y_train)
print("LR R2:", r2_score(y_test, lr.predict(X_test)))

LR R2: 0.9975247156529433

In [131]:
rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)
print("RF R2:", r2_score(y_test, rf.predict(X_test)))

RF R2: 0.9985196943643541

In [132]:
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

svr = SVR(C=100)
svr.fit(X_train_s, y_train)

print("SVR R2:", r2_score(y_test, svr.predict(X_test_s)))

SVR R2: 0.9875625888962997

In [133]:
X_cls = X
y_cls = df["battery_state_enc"]

X_train, X_test, y_train, y_test = train_test_split(
    X_cls, y_cls, test_size=0.2, random_state=42
)

In [134]:
log = LogisticRegression(max_iter=300)
log.fit(X_train, y_train)

pred = log.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Accuracy: 0.9
              precision    recall  f1-score   support

           0       0.94      0.89      0.92       146
           1       0.75      0.71      0.73        21
           2       0.87      0.97      0.92        73

    accuracy                           0.90       240
   macro avg       0.85      0.86      0.85       240
weighted avg       0.90      0.90      0.90       240

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [135]:
rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Accuracy: 0.9541666666666667
              precision    recall  f1-score   support

           0       0.97      0.95      0.96       146
           1       0.94      0.81      0.87        21
           2       0.92      1.00      0.96        73

    accuracy                           0.95       240
   macro avg       0.95      0.92      0.93       240
weighted avg       0.96      0.95      0.95       240

In [138]:
import joblib

print("\n========== SAVING BEST MODELS ==========")

# Save models
joblib.dump(model, "battery_health_model.pkl")
print("Saved: battery_health_model.pkl (Linear Regression)")

joblib.dump(lr, "rul_model.pkl")
print("Saved: rul_model.pkl (Linear Regression)")

joblib.dump(rf, "battery_state_model.pkl")
print("Saved: battery_state_model.pkl (Random Forest Classifier)")

========== SAVING BEST MODELS ==========
Saved: battery_health_model.pkl (Linear Regression)
Saved: rul_model.pkl (Linear Regression)
Saved: battery_state_model.pkl (Random Forest Classifier)

In [136]:
sample = pd.DataFrame([{
    "cycle_count": 500,
    "avg_speed": 60,
    "avg_voltage": 230,
    "avg_temp": 32,
    "voltage_drop_rate": 0.05
}])

health_pred = model.predict(sample)[0]
rul_pred = lr.predict(sample)[0]
state_pred = le.inverse_transform(log.predict(sample))[0]

print("Battery Health:", round(health_pred, 2))
print("RUL Cycles:", int(rul_pred))
print("Battery State:", state_pred)

Battery Health: 62.1
RUL Cycles: 2225
Battery State: Degrading

In [139]:
sample = pd.DataFrame([{
    "cycle_count": 300,
    "avg_speed": 55,
    "avg_voltage": 225,
    "avg_temp": 30,
    "voltage_drop_rate": 0.04
}])

print("Prediction Set 1")
print("Battery Health:", model.predict(sample)[0])
print("RUL:", lr.predict(sample)[0])
print("State:", le.inverse_transform(log.predict(sample))[0])

Prediction Set 1
Battery Health: 73.39999999999904
RUL: 2944.6924985561714
State: Degrading

In [140]:
sample = pd.DataFrame([{
    "cycle_count": 900,
    "avg_speed": 70,
    "avg_voltage": 240,
    "avg_temp": 38,
    "voltage_drop_rate": 0.09
}])

print("Prediction Set 2")
print("Battery Health:", model.predict(sample)[0])
print("RUL:", lr.predict(sample)[0])
print("State:", le.inverse_transform(log.predict(sample))[0])

Prediction Set 2
Battery Health: 35.30000000000062
RUL: 652.5948858427264
State: Warning

In [141]:
sample = pd.DataFrame([{
    "cycle_count": 1100,
    "avg_speed": 80,
    "avg_voltage": 245,
    "avg_temp": 40,
    "voltage_drop_rate": 0.11
}])

print("Prediction Set 3")
print("Battery Health:", model.predict(sample)[0])
print("RUL:", lr.predict(sample)[0])
print("State:", le.inverse_transform(log.predict(sample))[0])

Prediction Set 3
Battery Health: 23.10000000000103
RUL: -76.0045709496917
State: Warning

In [142]:
sample = pd.DataFrame([{
    "cycle_count": 150,
    "avg_speed": 50,
    "avg_voltage": 220,
    "avg_temp": 29,
    "voltage_drop_rate": 0.03
}])

print("NORMAL BATTERY SAMPLE")
print("Battery Health:", round(model.predict(sample)[0], 2))
print("RUL Cycles:", int(lr.predict(sample)[0]))
print("Battery State:", le.inverse_transform(log.predict(sample))[0])

NORMAL BATTERY SAMPLE
Battery Health: 81.5
RUL Cycles: 3457
Battery State: Normal